### ISSUE TITLE
Server issue

### ISSUE THREAD

**Issue by ichbinedgar** [pro-react/react-app-advanced-boilerplate#2]
Hi,
How can I add server files where I can manage the back-end (the api/endpoints or database)?

**Comment by cassiozen** [comment]
You can either develop and host the API separately or do everything as a node.js express app. Take a look at [webpack-express-boilerplate by christianalfoni](//github.com/christianalfoni/webpack-express-boilerplate) for an insight on the last option.

**Comment by ichbinedgar** [comment]
thanks
